// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recon.sql

package recondb

import (
	"context"

	"github.com/google/uuid"
)

const findCompletedRunByFingerprint = `-- name: FindCompletedRunByFingerprint :one
SELECT id, started_at, finished_at, internal_source, external_source, status, matched_count, exception_count, summary FROM recon_runs
WHERE status = 'completed'
  AND summary->>'input_fingerprint' = $1::text
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) FindCompletedRunByFingerprint(ctx context.Context, dollar_1 string) (ReconRun, error) {
	row := q.db.QueryRow(ctx, findCompletedRunByFingerprint, dollar_1)
	var i ReconRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.InternalSource,
		&i.ExternalSource,
		&i.Status,
		&i.MatchedCount,
		&i.ExceptionCount,
		&i.Summary,
	)
	return i, err
}

const finishReconRun = `-- name: FinishReconRun :one
UPDATE recon_runs
SET finished_at     = now(),
    status          = 'completed',
    matched_count   = $2,
    exception_count = $3,
    summary         = $4
WHERE id = $1
RETURNING id, started_at, finished_at, internal_source, external_source, status, matched_count, exception_count, summary
`

type FinishReconRunParams struct {
	ID             uuid.UUID `json:"id"`
	MatchedCount   int32     `json:"matched_count"`
	ExceptionCount int32     `json:"exception_count"`
	Summary        []byte    `json:"summary"`
}

func (q *Queries) FinishReconRun(ctx context.Context, arg FinishReconRunParams) (ReconRun, error) {
	row := q.db.QueryRow(ctx, finishReconRun,
		arg.ID,
		arg.MatchedCount,
		arg.ExceptionCount,
		arg.Summary,
	)
	var i ReconRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.InternalSource,
		&i.ExternalSource,
		&i.Status,
		&i.MatchedCount,
		&i.ExceptionCount,
		&i.Summary,
	)
	return i, err
}

const insertReconException = `-- name: InsertReconException :one
INSERT INTO recon_exceptions (run_id, category, reference, internal_record, external_record, delta_minor)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, run_id, category, reference, internal_record, external_record, delta_minor, created_at
`

type InsertReconExceptionParams struct {
	RunID          uuid.UUID `json:"run_id"`
	Category       string    `json:"category"`
	Reference      *string   `json:"reference"`
	InternalRecord []byte    `json:"internal_record"`
	ExternalRecord []byte    `json:"external_record"`
	DeltaMinor     *int64    `json:"delta_minor"`
}

func (q *Queries) InsertReconException(ctx context.Context, arg InsertReconExceptionParams) (ReconException, error) {
	row := q.db.QueryRow(ctx, insertReconException,
		arg.RunID,
		arg.Category,
		arg.Reference,
		arg.InternalRecord,
		arg.ExternalRecord,
		arg.DeltaMinor,
	)
	var i ReconException
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Category,
		&i.Reference,
		&i.InternalRecord,
		&i.ExternalRecord,
		&i.DeltaMinor,
		&i.CreatedAt,
	)
	return i, err
}

const insertReconRun = `-- name: InsertReconRun :one
INSERT INTO recon_runs (internal_source, external_source, status)
VALUES ($1, $2, 'running')
RETURNING id, started_at, finished_at, internal_source, external_source, status, matched_count, exception_count, summary
`

type InsertReconRunParams struct {
	InternalSource string `json:"internal_source"`
	ExternalSource string `json:"external_source"`
}

func (q *Queries) InsertReconRun(ctx context.Context, arg InsertReconRunParams) (ReconRun, error) {
	row := q.db.QueryRow(ctx, insertReconRun, arg.InternalSource, arg.ExternalSource)
	var i ReconRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.InternalSource,
		&i.ExternalSource,
		&i.Status,
		&i.MatchedCount,
		&i.ExceptionCount,
		&i.Summary,
	)
	return i, err
}
