// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balances.sql

package ledgerdb

import (
	"context"

	"github.com/google/uuid"
)

const getCachedBalance = `-- name: GetCachedBalance :one
SELECT account_id, balance_minor, currency, updated_at FROM account_balances
WHERE account_id = $1
`

func (q *Queries) GetCachedBalance(ctx context.Context, accountID uuid.UUID) (AccountBalance, error) {
	row := q.db.QueryRow(ctx, getCachedBalance, accountID)
	var i AccountBalance
	err := row.Scan(
		&i.AccountID,
		&i.BalanceMinor,
		&i.Currency,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCachedBalance = `-- name: UpsertCachedBalance :exec
INSERT INTO account_balances (account_id, balance_minor, currency, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (account_id) DO UPDATE
SET balance_minor = EXCLUDED.balance_minor,
    currency      = EXCLUDED.currency,
    updated_at    = now()
`

type UpsertCachedBalanceParams struct {
	AccountID    uuid.UUID `json:"account_id"`
	BalanceMinor int64     `json:"balance_minor"`
	Currency     string    `json:"currency"`
}

func (q *Queries) UpsertCachedBalance(ctx context.Context, arg UpsertCachedBalanceParams) error {
	_, err := q.db.Exec(ctx, upsertCachedBalance, arg.AccountID, arg.BalanceMinor, arg.Currency)
	return err
}
