// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package ledgerdb

import (
	"context"

	"github.com/google/uuid"
)

const insertEntry = `-- name: InsertEntry :one
INSERT INTO entries (transaction_id, account_id, direction, amount_minor, currency)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, transaction_id, account_id, direction, amount_minor, currency, created_at
`

type InsertEntryParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	AccountID     uuid.UUID `json:"account_id"`
	Direction     string    `json:"direction"`
	AmountMinor   int64     `json:"amount_minor"`
	Currency      string    `json:"currency"`
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, insertEntry,
		arg.TransactionID,
		arg.AccountID,
		arg.Direction,
		arg.AmountMinor,
		arg.Currency,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountID,
		&i.Direction,
		&i.AmountMinor,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const listEntriesByAccount = `-- name: ListEntriesByAccount :many
SELECT id, transaction_id, account_id, direction, amount_minor, currency, created_at FROM entries
WHERE account_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListEntriesByAccount(ctx context.Context, accountID uuid.UUID) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Direction,
			&i.AmountMinor,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByTransaction = `-- name: ListEntriesByTransaction :many
SELECT id, transaction_id, account_id, direction, amount_minor, currency, created_at FROM entries
WHERE transaction_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListEntriesByTransaction(ctx context.Context, transactionID uuid.UUID) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Direction,
			&i.AmountMinor,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumEntriesByAccount = `-- name: SumEntriesByAccount :one
SELECT
    COALESCE(SUM(amount_minor) FILTER (WHERE direction = 'debit'), 0)::bigint  AS debit_minor,
    COALESCE(SUM(amount_minor) FILTER (WHERE direction = 'credit'), 0)::bigint AS credit_minor
FROM entries
WHERE account_id = $1
`

type SumEntriesByAccountRow struct {
	DebitMinor  int64 `json:"debit_minor"`
	CreditMinor int64 `json:"credit_minor"`
}

func (q *Queries) SumEntriesByAccount(ctx context.Context, accountID uuid.UUID) (SumEntriesByAccountRow, error) {
	row := q.db.QueryRow(ctx, sumEntriesByAccount, accountID)
	var i SumEntriesByAccountRow
	err := row.Scan(&i.DebitMinor, &i.CreditMinor)
	return i, err
}
