// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ledgerdb

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID `json:"id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type AccountBalance struct {
	AccountID    uuid.UUID `json:"account_id"`
	BalanceMinor int64     `json:"balance_minor"`
	Currency     string    `json:"currency"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Entry struct {
	ID            uuid.UUID `json:"id"`
	TransactionID uuid.UUID `json:"transaction_id"`
	AccountID     uuid.UUID `json:"account_id"`
	Direction     string    `json:"direction"`
	AmountMinor   int64     `json:"amount_minor"`
	Currency      string    `json:"currency"`
	CreatedAt     time.Time `json:"created_at"`
}

type IdempotencyKey struct {
	Key                string     `json:"key"`
	RequestFingerprint string     `json:"request_fingerprint"`
	TransactionID      *uuid.UUID `json:"transaction_id"`
	Response           []byte     `json:"response"`
	Status             string     `json:"status"`
	CreatedAt          time.Time  `json:"created_at"`
	ExpiresAt          *time.Time `json:"expires_at"`
}

type Outbox struct {
	ID            int64      `json:"id"`
	AggregateType string     `json:"aggregate_type"`
	AggregateID   uuid.UUID  `json:"aggregate_id"`
	EventType     string     `json:"event_type"`
	Payload       []byte     `json:"payload"`
	CreatedAt     time.Time  `json:"created_at"`
	PublishedAt   *time.Time `json:"published_at"`
	Attempts      int32      `json:"attempts"`
	NextAttemptAt time.Time  `json:"next_attempt_at"`
	LastError     *string    `json:"last_error"`
	DeadLetter    bool       `json:"dead_letter"`
}

type ReconException struct {
	ID             uuid.UUID `json:"id"`
	RunID          uuid.UUID `json:"run_id"`
	Category       string    `json:"category"`
	Reference      *string   `json:"reference"`
	InternalRecord []byte    `json:"internal_record"`
	ExternalRecord []byte    `json:"external_record"`
	DeltaMinor     *int64    `json:"delta_minor"`
	CreatedAt      time.Time `json:"created_at"`
}

type ReconRun struct {
	ID             uuid.UUID  `json:"id"`
	StartedAt      time.Time  `json:"started_at"`
	FinishedAt     *time.Time `json:"finished_at"`
	InternalSource string     `json:"internal_source"`
	ExternalSource string     `json:"external_source"`
	Status         string     `json:"status"`
	MatchedCount   int32      `json:"matched_count"`
	ExceptionCount int32      `json:"exception_count"`
	Summary        []byte     `json:"summary"`
}

type Transaction struct {
	ID                  uuid.UUID  `json:"id"`
	Reference           string     `json:"reference"`
	Type                string     `json:"type"`
	Status              string     `json:"status"`
	IdempotencyKey      *string    `json:"idempotency_key"`
	ParentTransactionID *uuid.UUID `json:"parent_transaction_id"`
	Currency            string     `json:"currency"`
	InitiatedAt         time.Time  `json:"initiated_at"`
	SettledAt           *time.Time `json:"settled_at"`
	Metadata            []byte     `json:"metadata"`
}
