// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package ledgerdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getTransaction = `-- name: GetTransaction :one
SELECT id, reference, type, status, idempotency_key, parent_transaction_id, currency, initiated_at, settled_at, metadata FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Type,
		&i.Status,
		&i.IdempotencyKey,
		&i.ParentTransactionID,
		&i.Currency,
		&i.InitiatedAt,
		&i.SettledAt,
		&i.Metadata,
	)
	return i, err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT id, reference, type, status, idempotency_key, parent_transaction_id, currency, initiated_at, settled_at, metadata FROM transactions
WHERE idempotency_key = $1
`

// Resolve the transaction a leg's idempotency key already produced, so a
// re-driven post becomes an idempotent no-op returning the existing id.
func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey *string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdempotencyKey, idempotencyKey)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Type,
		&i.Status,
		&i.IdempotencyKey,
		&i.ParentTransactionID,
		&i.Currency,
		&i.InitiatedAt,
		&i.SettledAt,
		&i.Metadata,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (
    reference, type, status, idempotency_key, parent_transaction_id, currency, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, reference, type, status, idempotency_key, parent_transaction_id, currency, initiated_at, settled_at, metadata
`

type InsertTransactionParams struct {
	Reference           string     `json:"reference"`
	Type                string     `json:"type"`
	Status              string     `json:"status"`
	IdempotencyKey      *string    `json:"idempotency_key"`
	ParentTransactionID *uuid.UUID `json:"parent_transaction_id"`
	Currency            string     `json:"currency"`
	Metadata            []byte     `json:"metadata"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.Reference,
		arg.Type,
		arg.Status,
		arg.IdempotencyKey,
		arg.ParentTransactionID,
		arg.Currency,
		arg.Metadata,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Type,
		&i.Status,
		&i.IdempotencyKey,
		&i.ParentTransactionID,
		&i.Currency,
		&i.InitiatedAt,
		&i.SettledAt,
		&i.Metadata,
	)
	return i, err
}

const listTransactionsByWindow = `-- name: ListTransactionsByWindow :many
SELECT id, reference, type, status, idempotency_key, parent_transaction_id, currency, initiated_at, settled_at, metadata FROM transactions
WHERE initiated_at >= $1
  AND initiated_at < $2
ORDER BY initiated_at, id
`

type ListTransactionsByWindowParams struct {
	InitiatedAt   time.Time `json:"initiated_at"`
	InitiatedAt_2 time.Time `json:"initiated_at_2"`
}

func (q *Queries) ListTransactionsByWindow(ctx context.Context, arg ListTransactionsByWindowParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByWindow, arg.InitiatedAt, arg.InitiatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.Type,
			&i.Status,
			&i.IdempotencyKey,
			&i.ParentTransactionID,
			&i.Currency,
			&i.InitiatedAt,
			&i.SettledAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
