// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package switchdb

import (
	"context"

	"github.com/google/uuid"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET status = $2,
    response = $3,
    transaction_id = $4
WHERE key = $1
`

type CompleteIdempotencyKeyParams struct {
	Key           string     `json:"key"`
	Status        string     `json:"status"`
	Response      []byte     `json:"response"`
	TransactionID *uuid.UUID `json:"transaction_id"`
}

// Record the terminal outcome for a previously reserved key.
func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.Key,
		arg.Status,
		arg.Response,
		arg.TransactionID,
	)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, request_fingerprint, transaction_id, response, status, created_at, expires_at FROM idempotency_keys
WHERE key = $1
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.RequestFingerprint,
		&i.TransactionID,
		&i.Response,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const reserveIdempotencyKey = `-- name: ReserveIdempotencyKey :one
INSERT INTO idempotency_keys (key, request_fingerprint, status)
VALUES ($1, $2, 'in_progress')
ON CONFLICT (key) DO NOTHING
RETURNING key, request_fingerprint, transaction_id, response, status, created_at, expires_at
`

type ReserveIdempotencyKeyParams struct {
	Key                string `json:"key"`
	RequestFingerprint string `json:"request_fingerprint"`
}

// Atomically claim a key. ON CONFLICT DO NOTHING means a second concurrent
// caller gets no row back (pgx.ErrNoRows) rather than an error, so the Go layer
// can fall through to GetIdempotencyKey and inspect the existing record.
func (q *Queries) ReserveIdempotencyKey(ctx context.Context, arg ReserveIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, reserveIdempotencyKey, arg.Key, arg.RequestFingerprint)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.RequestFingerprint,
		&i.TransactionID,
		&i.Response,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
