// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package switchdb

import (
	"context"

	"github.com/google/uuid"
)

const claimOutboxBatch = `-- name: ClaimOutboxBatch :many
UPDATE outbox
SET next_attempt_at = now() + make_interval(secs => $1)
WHERE id IN (
    SELECT id FROM outbox
    WHERE published_at IS NULL AND dead_letter = false AND next_attempt_at <= now()
    ORDER BY created_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, aggregate_type, aggregate_id, event_type, payload, created_at, published_at, attempts, next_attempt_at, last_error, dead_letter
`

type ClaimOutboxBatchParams struct {
	Secs  float64 `json:"secs"`
	Limit int32   `json:"limit"`
}

// Atomically claim up to $2 due events, hiding them for $1 seconds (a short
// lease) so a crash mid-delivery re-surfaces the event. All timing is computed
// against the DB clock (now()) to stay consistent with the claim predicate.
// FOR UPDATE SKIP LOCKED lets multiple pollers run without contending.
func (q *Queries) ClaimOutboxBatch(ctx context.Context, arg ClaimOutboxBatchParams) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, claimOutboxBatch, arg.Secs, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.DeadLetter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDeadLetterOutbox = `-- name: CountDeadLetterOutbox :one
SELECT count(*) FROM outbox WHERE dead_letter = true
`

func (q *Queries) CountDeadLetterOutbox(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDeadLetterOutbox)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deadLetterOutbox = `-- name: DeadLetterOutbox :exec
UPDATE outbox
SET attempts = attempts + 1, dead_letter = true, last_error = $2
WHERE id = $1
`

type DeadLetterOutboxParams struct {
	ID        int64   `json:"id"`
	LastError *string `json:"last_error"`
}

// Park a poison event so it stops being claimed (it has hit the attempt cap).
func (q *Queries) DeadLetterOutbox(ctx context.Context, arg DeadLetterOutboxParams) error {
	_, err := q.db.Exec(ctx, deadLetterOutbox, arg.ID, arg.LastError)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO outbox (aggregate_type, aggregate_id, event_type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertOutboxEventParams struct {
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
}

// Append a follow-up event. Called with a tx-scoped Queries so the event
// commits in the same transaction as the state change that produced it.
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox SET published_at = now() WHERE id = $1
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}

const outboxLagSeconds = `-- name: OutboxLagSeconds :one
SELECT COALESCE(EXTRACT(EPOCH FROM now() - min(created_at)), 0)::float8 AS lag_seconds
FROM outbox
WHERE published_at IS NULL AND dead_letter = false
`

// Age of the oldest still-deliverable event, for the outbox_lag gauge.
func (q *Queries) OutboxLagSeconds(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, outboxLagSeconds)
	var lag_seconds float64
	err := row.Scan(&lag_seconds)
	return lag_seconds, err
}

const rescheduleOutbox = `-- name: RescheduleOutbox :exec
UPDATE outbox
SET attempts = attempts + 1, next_attempt_at = now() + make_interval(secs => $2), last_error = $3
WHERE id = $1
`

type RescheduleOutboxParams struct {
	ID        int64   `json:"id"`
	Secs      float64 `json:"secs"`
	LastError *string `json:"last_error"`
}

// Record a failed delivery and back the event off by $2 seconds (DB clock).
func (q *Queries) RescheduleOutbox(ctx context.Context, arg RescheduleOutboxParams) error {
	_, err := q.db.Exec(ctx, rescheduleOutbox, arg.ID, arg.Secs, arg.LastError)
	return err
}
