// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package switchdb

import (
	"context"

	"github.com/google/uuid"
)

const getTransferByID = `-- name: GetTransferByID :one
SELECT id, reference, type, status, idempotency_key, parent_transaction_id, currency, initiated_at, settled_at, metadata FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransferByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransferByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Type,
		&i.Status,
		&i.IdempotencyKey,
		&i.ParentTransactionID,
		&i.Currency,
		&i.InitiatedAt,
		&i.SettledAt,
		&i.Metadata,
	)
	return i, err
}

const getTransferForUpdate = `-- name: GetTransferForUpdate :one
SELECT id, reference, type, status, idempotency_key, parent_transaction_id, currency, initiated_at, settled_at, metadata FROM transactions
WHERE id = $1
FOR UPDATE
`

// Lock the transfer row so a status advance (settle / reverse / callback) is
// serialized against any other driver or callback touching the same transfer.
func (q *Queries) GetTransferForUpdate(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransferForUpdate, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Type,
		&i.Status,
		&i.IdempotencyKey,
		&i.ParentTransactionID,
		&i.Currency,
		&i.InitiatedAt,
		&i.SettledAt,
		&i.Metadata,
	)
	return i, err
}

const insertTransfer = `-- name: InsertTransfer :one
INSERT INTO transactions (reference, type, status, idempotency_key, currency, metadata)
VALUES ($1, 'transfer', $2, $3, $4, $5)
RETURNING id, reference, type, status, idempotency_key, parent_transaction_id, currency, initiated_at, settled_at, metadata
`

type InsertTransferParams struct {
	Reference      string  `json:"reference"`
	Status         string  `json:"status"`
	IdempotencyKey *string `json:"idempotency_key"`
	Currency       string  `json:"currency"`
	Metadata       []byte  `json:"metadata"`
}

// Create the transfer's lifecycle row. type is always 'transfer'; status starts
// at the coarse 'pending'. idempotency_key is the caller's Idempotency-Key.
// metadata carries source/destination/amount_minor for the read model (those
// live in ledger entries, not on this row).
func (q *Queries) InsertTransfer(ctx context.Context, arg InsertTransferParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, insertTransfer,
		arg.Reference,
		arg.Status,
		arg.IdempotencyKey,
		arg.Currency,
		arg.Metadata,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Type,
		&i.Status,
		&i.IdempotencyKey,
		&i.ParentTransactionID,
		&i.Currency,
		&i.InitiatedAt,
		&i.SettledAt,
		&i.Metadata,
	)
	return i, err
}

const listResumableTransfers = `-- name: ListResumableTransfers :many
SELECT id, reference, type, status, idempotency_key, parent_transaction_id, currency, initiated_at, settled_at, metadata FROM transactions
WHERE type = 'transfer'
  AND status IN ('pending','debited','in_doubt','reversal_pending')
ORDER BY initiated_at
`

// Non-terminal transfers, for the recovery sweep (NS-306). Ordered oldest-first.
func (q *Queries) ListResumableTransfers(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listResumableTransfers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.Type,
			&i.Status,
			&i.IdempotencyKey,
			&i.ParentTransactionID,
			&i.Currency,
			&i.InitiatedAt,
			&i.SettledAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTransferSettled = `-- name: SetTransferSettled :exec
UPDATE transactions
SET status = 'settled', settled_at = now()
WHERE id = $1
`

func (q *Queries) SetTransferSettled(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setTransferSettled, id)
	return err
}

const setTransferStatus = `-- name: SetTransferStatus :exec
UPDATE transactions
SET status = $2
WHERE id = $1
`

type SetTransferStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetTransferStatus(ctx context.Context, arg SetTransferStatusParams) error {
	_, err := q.db.Exec(ctx, setTransferStatus, arg.ID, arg.Status)
	return err
}

const setTransferStatusAndDebitLeg = `-- name: SetTransferStatusAndDebitLeg :exec
UPDATE transactions
SET status = $1,
    metadata = metadata || jsonb_build_object('debit_leg_tx_id', $2::text)
WHERE id = $3
`

type SetTransferStatusAndDebitLegParams struct {
	Status       string    `json:"status"`
	DebitLegTxID string    `json:"debit_leg_tx_id"`
	ID           uuid.UUID `json:"id"`
}

// Advance to 'debited' and record the debit leg's ledger transaction id (the
// reversal parent) in metadata, in one statement.
func (q *Queries) SetTransferStatusAndDebitLeg(ctx context.Context, arg SetTransferStatusAndDebitLegParams) error {
	_, err := q.db.Exec(ctx, setTransferStatusAndDebitLeg, arg.Status, arg.DebitLegTxID, arg.ID)
	return err
}
